const GET_RECIPES = "GET_RECIPES";
const SEARCH_RECIPES = "SEARCH_RECIPES";
const GET_RECIPE_DETAIL = "GET_RECIPE_DETAIL";
const CLEAR_DETAIL = "CLEAR_DETAIL";
const POST_NEW_RECIPE = "POST_NEW_RECIPE";
const GET_TYPES_OF_DIETS = "GET_TYPES_OF_DIETS";
const FILTER_BY_TYPE_OF_DIET = "FILTER_BY_TYPE_OF_DIET";
const SORT = "SORT";
const SORT_BY_SCORE = "SORT_BY_SCORE";

module.exports = {
  GET_RECIPES,
  SEARCH_RECIPES,
  GET_RECIPE_DETAIL,
  CLEAR_DETAIL,
  POST_NEW_RECIPE,
  GET_TYPES_OF_DIETS,
  FILTER_BY_TYPE_OF_DIET,
  SORT,
  SORT_BY_SCORE,
};
