const GET_RECIPES = "GET_RECIPES";
const SEARCH_RECIPES = "SEARCH_RECIPES";
const GET_RECIPE_DETAIL = "GET_RECIPE_DETAIL";
const CLEAR_DETAIL = "CLEAR_DETAIL";
const POST_NEW_RECIPE = "POST_NEW_RECIPE";

module.exports = {
  GET_RECIPES,
  SEARCH_RECIPES,
  GET_RECIPE_DETAIL,
  CLEAR_DETAIL,
  POST_NEW_RECIPE,
};
